### ISSUE TITLE
does not build with gcc 7

### ISSUE THREAD

**Issue by callalilychen** [IBM/gWhisper#61] opened 2019-07-29 14:57 UTC
**Describe the bug**
I got the following compile error, as I try to compile gwisper with `build.sh`:
[ 35%] Building CXX object third_party/gRPC_utils/CMakeFiles/reflection.dir/cli_call.cc.o
cd /home/chw2lr/tools/gWhisper/build/third_party/gRPC_utils && /usr/bin/c++   -I/home/chw2lr/tools/gWhisper/build -I/home/chw2lr/tools/gWhisper/build/src -I/home/chw2lr/tools/gWhisper -I/home/chw2lr/tools/gWhisper/src -I/home/chw2lr/tools/gWhisper/build/third_party/gRPC_utils  -std=gnu++11 -o CMakeFiles/reflection.dir/cli_call.cc.o -c /home/chw2lr/tools/gWhisper/third_party/gRPC_utils/cli_call.cc
In file included from /home/chw2lr/tools/gWhisper/third_party/gRPC_utils/cli_call.cc:21:0:
/home/chw2lr/tools/gWhisper/third_party/gRPC_utils/cli_call.h:32:7: error: using typedef-name ‘grpc::ClientContext’ after ‘class’
 class ClientContext;
       ^~~~~~~~~~~~~
In file included from /usr/local/include/grpcpp/impl/codegen/call_op_set.h:34:0,
                 from /usr/local/include/grpcpp/impl/codegen/server_context_impl.h:28,
                 from /usr/local/include/grpcpp/impl/codegen/server_context.h:22,
                 from /usr/local/include/grpcpp/impl/codegen/async_stream.h:25,
                 from /usr/local/include/grpcpp/support/async_stream.h:22,
                 from /usr/local/include/grpcpp/generic/generic_stub_impl.h:24,
                 from /usr/local/include/grpcpp/generic/generic_stub.h:22,
                 from /home/chw2lr/tools/gWhisper/third_party/gRPC_utils/cli_call.h:26,
                 from /home/chw2lr/tools/gWhisper/third_party/gRPC_utils/cli_call.cc:21:
/usr/local/include/grpcpp/impl/codegen/client_context.h:26:36: note: ‘grpc::ClientContext’ has a previous declaration here
 typedef ::grpc_impl::ClientContext ClientContext;
                                    ^~~~~~~~~~~~~
third_party/gRPC_utils/CMakeFiles/reflection.dir/build.make:100: recipe for target 'third_party/gRPC_utils/CMakeFiles/reflection.dir/cli_call.cc.o' failed
make[2]: *** [third_party/gRPC_utils/CMakeFiles/reflection.dir/cli_call.cc.o] Error 1
```
```

**To Reproduce**
./build.sh 

with 
```
$ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Expected behavior**
It compiled.

**Provide details about your environment**
 - Operating System version:
 - `gwhisper --version` output: -
 - gRPC/protobuf version: how to find it out?
 - Compiler version (if related to build): see above
 - CMake version (if related to build):

```
 cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by rainerschoe** [comment] 2019-07-29 15:33
Thanks for reporting.

The problem is located in third-party code inherited from the gRPC project.
We need to figure out a strategy on how to update/fix or ignore errors in this files.

This might me related to other grpc build issues see [link](https://github.com/grpc/grpc/issues/15576)

In the meantime you might want to consider using clang instead of gcc:
```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
```

**Comment by rainerschoe** [comment] 2019-07-30 09:57
This is already fixed in latest gRPC version. I will update the third-party directory to contain the latest gRPC code

**Comment by rainerschoe** [comment] 2019-07-30 11:32
@callalilychen could you please test if this is resolved with https://github.com/IBM/gWhisper/pull/62
I do not have gcc7 available here.

**Closed** 2019-08-03 06:54 UTC
Labels: High Priority, bug

**Comment by callalilychen** [comment] 2019-08-05 14:10
it works, thanks :)
